# source: https://github.com/TRIGONIM/lua-gmod-lib/blob/main/.github/workflows/release.yml
name: "luarocks-release"
on:
  push:
    tags:
      - 'v*'
jobs:
  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          name: ggram-test # не влияет на require
          license: "MIT"
          summary: "ggram – Lua Telegram Bot Framework"
          detailed_description: |
            Create Telegram bots of any complexity in pure Lua
            More info: https://github.com/TRIGONIM/ggram/
          dependencies: |
            copas >= 4.3.0
            luasec
            lua-cjson
            lua-requests-async
            lua-gmod-lib
          labels: |
            telegram
            bot
            api
            copas
          # copy_directories: |
          #   dir
